### ISSUE TITLE
X server requires "randrproto >= 1.6.0"

### ISSUE THREAD

**Issue by whoman321** [JeffyCN/xorg-xserver#1]
Hello,
I'm trying to test xvimagesink on rk3328

because rk3328 SDK is only on STRETCH, I cannot compile this xorg-xserver on STRETCH.

Is there a branch that does not require randrproto >= 1.6.0?

**Comment by JeffyCN** [comment]
There's a debian/1.19.2-1+deb9u5 branch for original stretch. But we are actually building the 1.20.x by switching to the buster apt sources and installing related build-deps.
