### ISSUE TITLE
RK3588 debian 内存泄露

### ISSUE THREAD

**Issue by zhouxl6** [JeffyCN/xorg-xserver#10]
在正常运行的情况下，Xorg 会不断申请 drmbuf ，但是没有释放。以下有三个日志文件
log0 ：运行一会后，rockchipdrm 使用情况
log1 ：再大概运行几分钟后，rockchipdrm 使用情况，相对 log0 ，只有新增加的 rockchipdrm 使用，并未发现有释放的
log2 ：重新启动 lightdm 服务后，rockchipdrm 使用情况，发现在 Xorg 服务重启启动后，rockchipdrm 有释放

日志文件均使用命令 cat /proc/rk_dmabuf/dev > logx 生成
[log3.log](https://github.com/JeffyCN/xorg-xserver/files/9544108/log3.log)
[log0.log](https://github.com/JeffyCN/xorg-xserver/files/9544109/log0.log)
[log2.log](https://github.com/JeffyCN/xorg-xserver/files/9544110/log2.log)

**Comment by JeffyCN** [comment]
unlikely related to xserver.

xserver is acting like an remote allocator, so you have some apps leaking pixmap memory.
