### ISSUE TITLE
[GUIDE] Can you guide me to build debian packages for this repositories?   

### ISSUE THREAD

**Issue by UtsavBalar1231** [JeffyCN/xorg-xserver#13]
Hey jeffy, I want to use updated Xorg with my RK3399 board, I am not able to get accelerated DRM to work on Rockchip debian, From the glxinfo results it fails to load rockchip dri and the DRM is offload onto the CPU itself.

It seems like mesa and Xorg is outdated and needs to be updated to get the DRM offloaded to MALI.

Can you guide me in the correct direction?

**Comment by JeffyCN** [comment]
rk3399 is using mali gpu, the arm's mali ddk will not support glx(it would provide gles instead).

if you want glx, maybe try to search opensource driver such as lima/panfrost with mesa3d and official xserver instead.

**Comment by UtsavBalar1231** [comment]
Yeah I have tried Panfrost with the mainline kernel, It works well. But its not a stable solution as other things break with that kernel. Rockchip 5.10 kernel is very stable and I am able to get the GL support by using GL4ES opensource utility, Still was hoping if there is possible way to get DRM on Mali instead.

**Comment by JeffyCN** [comment]
the gl4es is not that stable, i've tried it with debian, but cause lots of abnormal ui.

anyway, if you try to build deb, you can use the related debian branch(or port patches to the ubuntu official branch), then build it on the device(with mali deb uninstalled). the command would be something like dpkg-buildpackage -us -uc

**Comment by UtsavBalar1231** [comment]
Alright, My final question is that the RK3399 datasheet says that Mali GPU supports GLES3.x specifications right. So in theory, My graphics applications should work with GLES3 api, but running that application under Rockchip debian, only offloads it to CPU (LLVM pipe) instead. For this reason only I wanted to try the latest Xorg and Mesa. 

Am I doing this incorrect ? I just want to use OpenGL3 ES applications on RK3399 :(

BTW thankyou for all your efforts with Rockchip applications

**Comment by JeffyCN** [comment]
it supports gles3(3.2 i think), not glx.

to use that, you may need this hacked xserver with libmali installed to enable xserver glamor accel to provide dri2(mali client use dri2).

**Comment by UtsavBalar1231** [comment]
Thanks for all the information, closing this down
