### ISSUE TITLE
configure.ac:38: error: must install xorg-macros 1.14 or later before running autoconf/autogen

### ISSUE THREAD

**Issue by ck167493** [JeffyCN/xorg-xserver#14]
在yocto中运行脚本中调用了autogen.sh脚本，其中autoreconf --force -v --install || exit 1这一行，索引不到recipe-sysroot跟recipe-sysroot-native的环境，在yocto里面没有办法进行配置，这块有头绪怎么修复吗？

**Comment by JeffyCN** [comment]
i've uploaded 2 commits about that, please try to update your meta-rockchip.
