### ISSUE TITLE
XPutImage very slow

### ISSUE THREAD

**Issue by amazingfate** [JeffyCN/xorg-xserver#2]
I have a rk3288 board with xserver and libmali driver from https://github.com/JeffyCN/mirrors/tree/debian installed.
benchmark with command `x11perf -putimagexy500` resulted in 1.0/sec

**Comment by JeffyCN** [comment]
XPutImage with XYPixmap is expected to be slow(using software path), check:
https://github.com/JeffyCN/xorg-xserver/blob/1.20.4/exa/exa_accel.c#L161
https://github.com/JeffyCN/xorg-xserver/blob/1.20.4/glamor/glamor_image.c#L58
