### ISSUE TITLE
xserver will not compile. 

### ISSUE THREAD

**Issue by shawn-pfister** [JeffyCN/xorg-xserver#7]
There is an isssue in the repository for tag 1.20,14_2022_01_17

Line 729 in /hw/xfree86/drivers/modesetting/driver.c 

            drmmode_set_desired_modes(pScrn, &ms->drmmode, TRUE);

Line 1432 & 1411 in /hw/xfree86/drivers/modesetting/drmmode_display.c

           drmmode_set_desired_modes(scrn, &ms->drmmode, TRUE)

These  function calls don't match the prototype in drmmode_display.h

**Comment by JeffyCN** [comment]
thanks for reporting, patch uploaded.
